### ISSUE TITLE
Error None

### ISSUE THREAD

**Issue by ThijmHacks** [ThijmHacks/st_AI_n#2]
Traceback (most recent call last):
  File "C:\Users\thijm\OneDrive\Documenten\Programming\AI\st_AI_n\python\main.py", line 29, in <module>
    st_AI_n.responses.response(prompt)
  File "C:\Users\thijm\OneDrive\Documenten\Programming\AI\st_AI_n\python\st_AI_n\responses\__init__.py", line 4, in response
    print(st_AI_n.lists.randomanswer(st_AI_n.lists.checkindir(prompt)))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\thijm\OneDrive\Documenten\Programming\AI\st_AI_n\python\st_AI_n\lists\__init__.py", line 15, in randomanswer
    returnanswer = answers[string]
                   ~~~~~~~^^^^^^^^
KeyError: 'None'

**Comment by ThijmHacks** [comment]
This is now fixed. You should not get this error anymore.
